apiVersion: 1

datasources:
  - name: SQLite
    type: frser-sqlite-datasource
    access: proxy
    database: /app/data/cloud_costs.db
    jsonData:
      storage: file
      path: /app/data/cloud_costs.db
    editable: false
  
  - name: CloudCostsCSV
    type: marcusolsson-csv-datasource
    access: proxy
    isDefault: true
    jsonData:
      storage: local
      path: /app/data
    editable: true